# The URL of your authentication backend.
backendUrl: "http://10.1.1.231"

# The port on which your backend is running.
backendPort: 3000

# The access code used when communicating with the backend API.
access-code: "your_access_code_here"

# The public server ID used in the link sent to players.
server-id: "server-id-here"
